Add test cases for running guilt from $GUILT_DIR/$branch
The previous commit made many subcommands explicitly refuse to run
from $GUILT_DIR/$branch (which isn't a work tree).  Some other
commands have historically worked find when invoked from that
directory.  Add test cases for both classes of commands.

t-012.sh contains a table of all guilt commands, if they should be
runnable from within $GUILT_DIR/$branch, and where they are tested.
t-012.sh, t-013.sh and t-014.sh combined cover all subcommands, except
patchbomb and repair.

diff --git a/regression/scaffold b/regression/scaffold
--- a/regression/scaffold
+++ b/regression/scaffold
@@ -39,7 +39,8 @@ function replace_path
 	    -e "s,\.\.\. initial, initial,g" \
 	    -e "s,^Already on\( branch\)\? [\"']\([^\"']*\)[\"']$,Already on \"\2\",g" \
 	    -e "s,^Switched to branch [\"']\([^\"']*\)[\"'],Switched to branch \"\1\",g" \
-	    -e "\\,^Deleted branch guilt/.* (was .*).$,d"
+	    -e "\\,^Deleted branch guilt/.* (was .*).$,d" \
+	    -e "s,This operation must be run in a work tree,this operation must be run in a work tree,"
 }
 
 # Newer dd does
@@ -57,6 +58,21 @@ function cmd
 	if ! (
 		exec 3>&1
 		rv=`(("$@" 2>&1; echo $? >&4) | replace_path >&3 ) 4>&1`
+		exit $rv
+	) ; then
+		echo "% FAIL: The above command should succeed but failed."
+		exit 1
+	fi
+}
+
+# usage: cmd_silent <cmd>..
+# Like cmd, but discard the output from the command.
+function cmd_silent
+{
+	printf "%% %s\n" "$*" | replace_path
+	if ! (
+		exec 3>&1
+		rv=`(("$@" 2>&1 >/dev/null; echo $? >&4) | replace_path >&3 ) 4>&1`
 		exit $rv
 	) ; then
 		echo "% FAIL: The above command should succeed but failed."
