Improve error reporting for regression utilities
Output error messages on standard error.
Don't use "die", it's not available here.

Signed-off-by: Frediano Ziglio <freddy77@gmail.com>

diff --git a/regression/bin/dump_ref b/regression/bin/dump_ref
--- a/regression/bin/dump_ref
+++ b/regression/bin/dump_ref
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ $# -ne 1 ]; then
-	echo "ERROR"
+	echo "ERROR" >&2
 	exit 1
 fi
 
diff --git a/regression/bin/dump_reg b/regression/bin/dump_reg
--- a/regression/bin/dump_reg
+++ b/regression/bin/dump_reg
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 if [ $# -ne 1 ]; then
-	echo "ERROR"
+	echo "ERROR" >&2
 	exit 1
 fi
 
@@ -10,7 +10,8 @@ UNAME_S=`uname -s`
 if [ -r "$REG_DIR/../os.$UNAME_S" ]; then
 	. "$REG_DIR/../os.$UNAME_S"
 else
-	die "Unsupported operating system: $UNAME_S"
+	echo "Unsupported operating system: $UNAME_S" >&2
+	exit 1
 fi
 
 if [ -d "$1" ]; then
